//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAttribute
    {
        public int id { get; set; }
        public int refCategory { get; set; }
        public int refCategoryGroup { get; set; }
        public int refInputType { get; set; }
        public int refTranslationName { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> ShownInFilter { get; set; }
        public Nullable<bool> ShownInDetails { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual CategoryGroup CategoryGroup { get; set; }
        public virtual InputTypeEnum InputType { get; set; }
        public virtual Translation Translation { get; set; }
    }
}
