//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public int refCategory { get; set; }
        public int refTranslationName { get; set; }
        public int refTranslationSlug { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Translation Name { get; set; }
        public virtual Translation Slug { get; set; }
    }
}
